function phaseMapViewer(F, np, minmax)
%+Focused version of phaseMapViewer

if ~exist('minmax', 'var')
    min = 0;
    max = 10;
else
    min = minmax(1);
    max = minmax(2);
end

    switch np
        case 'signal neuron'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmnsig_amplitude'),...
                Focused.Mmap(F, 'pmnsig_deltaphi'),...
                [F.name ' phaseMap'],...
                min, max);
        case 'signal pixel'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmpsig_amplitude'),...
                Focused.Mmap(F, 'pmpsig_deltaphi'),...
                [F.name ' phaseMap'],...
                min, max);
        case 'dff neuron'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmndff_amplitude'),...
                Focused.Mmap(F, 'pmndff_deltaphi'),...
                [F.name ' phaseMap'],...
                min, max);
        case 'dff pixel'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmpdff_amplitude'),...
                Focused.Mmap(F, 'pmpdff_deltaphi'),...
                [F.name ' phaseMap'],...
                min, max);
    end

end 
