function phaseMapViewer(F, np,varargin)
%+Focused version of phaseMapViewer

if length(varargin)==1
    Max = varargin{1};
else
    Max = 100;
end
    switch np
        case 'signal neuron'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmnsig_amplitude'),...
                Focused.Mmap(F, 'pmnsig_deltaphi'),...
                [F.name ' phaseMap'],...
                Max);
        case 'signal pixel'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmpsig_amplitude'),...
                Focused.Mmap(F, 'pmpsig_deltaphi'),...
                [F.name ' phaseMap'],...
                Max);
        case 'dff neuron'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmndff_amplitude'),...
                Focused.Mmap(F, 'pmndff_deltaphi'),...
                [F.name ' phaseMap'],...
                Max);
        case 'dff pixel'
            phaseMapViewer(...
                Focused.Mmap(F, 'pmpdff_amplitude'),...
                Focused.Mmap(F, 'pmpdff_deltaphi'),...
                [F.name ' phaseMap'],...
                Max);
    end

end 
