function printPhaseMap(F, np, minmax)
%+Focused version of phaseMapViewer

    switch np
        case 'signal neuron'
            printPhaseMap(...
                F.dir('PhaseMapSignalNeuron'),...
                Focused.Mmap(F, 'pmnsig_amplitude'),...
                Focused.Mmap(F, 'pmnsig_deltaphi'),...
                [F.name ' phaseMap'],...
                minmax);
        case 'signal pixel'
            printPhaseMap(...
                F.dir('PhaseMapSignalPixel'),...
                Focused.Mmap(F, 'pmpsig_amplitude'),...
                Focused.Mmap(F, 'pmpsig_deltaphi'),...
                [F.name ' phaseMap'],...
                minmax);
        case 'dff neuron'
            printPhaseMap(...
                F.dir('PhaseMapDFFNeuron'),...
                Focused.Mmap(F, 'pmndff_amplitude'),...
                Focused.Mmap(F, 'pmndff_deltaphi'),...
                [F.name ' phaseMap'],...
                minmax);
        case 'dff pixel'
            printPhaseMap(...
                F.dir('PhaseMapDFFPixel'),...
                Focused.Mmap(F, 'pmpdff_amplitude'),...
                Focused.Mmap(F, 'pmpdff_deltaphi'),...
                [F.name ' phaseMap'],...
                minmax);
    end

end 
